// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: valorant_player_service.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetValorantProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetValorantProfileRequest) Reset() {
	*x = GetValorantProfileRequest{}
	mi := &file_valorant_player_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetValorantProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetValorantProfileRequest) ProtoMessage() {}

func (x *GetValorantProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_valorant_player_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetValorantProfileRequest.ProtoReflect.Descriptor instead.
func (*GetValorantProfileRequest) Descriptor() ([]byte, []int) {
	return file_valorant_player_service_proto_rawDescGZIP(), []int{0}
}

func (x *GetValorantProfileRequest) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

type GetValorantProfileResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Exists         bool                   `protobuf:"varint,1,opt,name=exists,proto3" json:"exists,omitempty"`
	PlayerId       string                 `protobuf:"bytes,2,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Nickname       string                 `protobuf:"bytes,3,opt,name=nickname,proto3" json:"nickname,omitempty"`
	RiotId         string                 `protobuf:"bytes,4,opt,name=riot_id,json=riotId,proto3" json:"riot_id,omitempty"`
	Region         string                 `protobuf:"bytes,5,opt,name=region,proto3" json:"region,omitempty"`
	CurrentRank    string                 `protobuf:"bytes,6,opt,name=current_rank,json=currentRank,proto3" json:"current_rank,omitempty"`
	MainRoles      []string               `protobuf:"bytes,7,rep,name=main_roles,json=mainRoles,proto3" json:"main_roles,omitempty"`
	Status         string                 `protobuf:"bytes,8,opt,name=status,proto3" json:"status,omitempty"`
	TeammateRating float64                `protobuf:"fixed64,9,opt,name=teammate_rating,json=teammateRating,proto3" json:"teammate_rating,omitempty"`
	ReviewsCount   int32                  `protobuf:"varint,10,opt,name=reviews_count,json=reviewsCount,proto3" json:"reviews_count,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetValorantProfileResponse) Reset() {
	*x = GetValorantProfileResponse{}
	mi := &file_valorant_player_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetValorantProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetValorantProfileResponse) ProtoMessage() {}

func (x *GetValorantProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_valorant_player_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetValorantProfileResponse.ProtoReflect.Descriptor instead.
func (*GetValorantProfileResponse) Descriptor() ([]byte, []int) {
	return file_valorant_player_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetValorantProfileResponse) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

func (x *GetValorantProfileResponse) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *GetValorantProfileResponse) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *GetValorantProfileResponse) GetRiotId() string {
	if x != nil {
		return x.RiotId
	}
	return ""
}

func (x *GetValorantProfileResponse) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *GetValorantProfileResponse) GetCurrentRank() string {
	if x != nil {
		return x.CurrentRank
	}
	return ""
}

func (x *GetValorantProfileResponse) GetMainRoles() []string {
	if x != nil {
		return x.MainRoles
	}
	return nil
}

func (x *GetValorantProfileResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetValorantProfileResponse) GetTeammateRating() float64 {
	if x != nil {
		return x.TeammateRating
	}
	return 0
}

func (x *GetValorantProfileResponse) GetReviewsCount() int32 {
	if x != nil {
		return x.ReviewsCount
	}
	return 0
}

type FindValorantPlayersRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	ExcludedPlayerId     string                 `protobuf:"bytes,1,opt,name=excluded_player_id,json=excludedPlayerId,proto3" json:"excluded_player_id,omitempty"`
	MinRank              string                 `protobuf:"bytes,2,opt,name=min_rank,json=minRank,proto3" json:"min_rank,omitempty"`
	MaxRank              string                 `protobuf:"bytes,3,opt,name=max_rank,json=maxRank,proto3" json:"max_rank,omitempty"`
	RequiredPlayerStatus string                 `protobuf:"bytes,4,opt,name=required_player_status,json=requiredPlayerStatus,proto3" json:"required_player_status,omitempty"`
	MinTeammateRating    float64                `protobuf:"fixed64,5,opt,name=min_teammate_rating,json=minTeammateRating,proto3" json:"min_teammate_rating,omitempty"`
	Region               string                 `protobuf:"bytes,6,opt,name=region,proto3" json:"region,omitempty"`
	RequiredRoles        []string               `protobuf:"bytes,7,rep,name=required_roles,json=requiredRoles,proto3" json:"required_roles,omitempty"`
	Limit                int32                  `protobuf:"varint,8,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *FindValorantPlayersRequest) Reset() {
	*x = FindValorantPlayersRequest{}
	mi := &file_valorant_player_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindValorantPlayersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindValorantPlayersRequest) ProtoMessage() {}

func (x *FindValorantPlayersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_valorant_player_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindValorantPlayersRequest.ProtoReflect.Descriptor instead.
func (*FindValorantPlayersRequest) Descriptor() ([]byte, []int) {
	return file_valorant_player_service_proto_rawDescGZIP(), []int{2}
}

func (x *FindValorantPlayersRequest) GetExcludedPlayerId() string {
	if x != nil {
		return x.ExcludedPlayerId
	}
	return ""
}

func (x *FindValorantPlayersRequest) GetMinRank() string {
	if x != nil {
		return x.MinRank
	}
	return ""
}

func (x *FindValorantPlayersRequest) GetMaxRank() string {
	if x != nil {
		return x.MaxRank
	}
	return ""
}

func (x *FindValorantPlayersRequest) GetRequiredPlayerStatus() string {
	if x != nil {
		return x.RequiredPlayerStatus
	}
	return ""
}

func (x *FindValorantPlayersRequest) GetMinTeammateRating() float64 {
	if x != nil {
		return x.MinTeammateRating
	}
	return 0
}

func (x *FindValorantPlayersRequest) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *FindValorantPlayersRequest) GetRequiredRoles() []string {
	if x != nil {
		return x.RequiredRoles
	}
	return nil
}

func (x *FindValorantPlayersRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ValorantPlayerCandidate struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	PlayerId       string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Nickname       string                 `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	RiotId         string                 `protobuf:"bytes,3,opt,name=riot_id,json=riotId,proto3" json:"riot_id,omitempty"`
	Region         string                 `protobuf:"bytes,4,opt,name=region,proto3" json:"region,omitempty"`
	CurrentRank    string                 `protobuf:"bytes,5,opt,name=current_rank,json=currentRank,proto3" json:"current_rank,omitempty"`
	MainRoles      []string               `protobuf:"bytes,6,rep,name=main_roles,json=mainRoles,proto3" json:"main_roles,omitempty"`
	Status         string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	TeammateRating float64                `protobuf:"fixed64,8,opt,name=teammate_rating,json=teammateRating,proto3" json:"teammate_rating,omitempty"`
	ReviewsCount   int32                  `protobuf:"varint,9,opt,name=reviews_count,json=reviewsCount,proto3" json:"reviews_count,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ValorantPlayerCandidate) Reset() {
	*x = ValorantPlayerCandidate{}
	mi := &file_valorant_player_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValorantPlayerCandidate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValorantPlayerCandidate) ProtoMessage() {}

func (x *ValorantPlayerCandidate) ProtoReflect() protoreflect.Message {
	mi := &file_valorant_player_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValorantPlayerCandidate.ProtoReflect.Descriptor instead.
func (*ValorantPlayerCandidate) Descriptor() ([]byte, []int) {
	return file_valorant_player_service_proto_rawDescGZIP(), []int{3}
}

func (x *ValorantPlayerCandidate) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *ValorantPlayerCandidate) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *ValorantPlayerCandidate) GetRiotId() string {
	if x != nil {
		return x.RiotId
	}
	return ""
}

func (x *ValorantPlayerCandidate) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *ValorantPlayerCandidate) GetCurrentRank() string {
	if x != nil {
		return x.CurrentRank
	}
	return ""
}

func (x *ValorantPlayerCandidate) GetMainRoles() []string {
	if x != nil {
		return x.MainRoles
	}
	return nil
}

func (x *ValorantPlayerCandidate) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ValorantPlayerCandidate) GetTeammateRating() float64 {
	if x != nil {
		return x.TeammateRating
	}
	return 0
}

func (x *ValorantPlayerCandidate) GetReviewsCount() int32 {
	if x != nil {
		return x.ReviewsCount
	}
	return 0
}

type FindValorantPlayersResponse struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Candidates    []*ValorantPlayerCandidate `protobuf:"bytes,1,rep,name=candidates,proto3" json:"candidates,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindValorantPlayersResponse) Reset() {
	*x = FindValorantPlayersResponse{}
	mi := &file_valorant_player_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindValorantPlayersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindValorantPlayersResponse) ProtoMessage() {}

func (x *FindValorantPlayersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_valorant_player_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindValorantPlayersResponse.ProtoReflect.Descriptor instead.
func (*FindValorantPlayersResponse) Descriptor() ([]byte, []int) {
	return file_valorant_player_service_proto_rawDescGZIP(), []int{4}
}

func (x *FindValorantPlayersResponse) GetCandidates() []*ValorantPlayerCandidate {
	if x != nil {
		return x.Candidates
	}
	return nil
}

type CheckValorantPlayerEligibilityRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	PlayerId             string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	MinRank              string                 `protobuf:"bytes,2,opt,name=min_rank,json=minRank,proto3" json:"min_rank,omitempty"`
	MaxRank              string                 `protobuf:"bytes,3,opt,name=max_rank,json=maxRank,proto3" json:"max_rank,omitempty"`
	RequiredPlayerStatus string                 `protobuf:"bytes,4,opt,name=required_player_status,json=requiredPlayerStatus,proto3" json:"required_player_status,omitempty"`
	MinTeammateRating    float64                `protobuf:"fixed64,5,opt,name=min_teammate_rating,json=minTeammateRating,proto3" json:"min_teammate_rating,omitempty"`
	Region               string                 `protobuf:"bytes,6,opt,name=region,proto3" json:"region,omitempty"`
	RequiredRoles        []string               `protobuf:"bytes,7,rep,name=required_roles,json=requiredRoles,proto3" json:"required_roles,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *CheckValorantPlayerEligibilityRequest) Reset() {
	*x = CheckValorantPlayerEligibilityRequest{}
	mi := &file_valorant_player_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckValorantPlayerEligibilityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckValorantPlayerEligibilityRequest) ProtoMessage() {}

func (x *CheckValorantPlayerEligibilityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_valorant_player_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckValorantPlayerEligibilityRequest.ProtoReflect.Descriptor instead.
func (*CheckValorantPlayerEligibilityRequest) Descriptor() ([]byte, []int) {
	return file_valorant_player_service_proto_rawDescGZIP(), []int{5}
}

func (x *CheckValorantPlayerEligibilityRequest) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *CheckValorantPlayerEligibilityRequest) GetMinRank() string {
	if x != nil {
		return x.MinRank
	}
	return ""
}

func (x *CheckValorantPlayerEligibilityRequest) GetMaxRank() string {
	if x != nil {
		return x.MaxRank
	}
	return ""
}

func (x *CheckValorantPlayerEligibilityRequest) GetRequiredPlayerStatus() string {
	if x != nil {
		return x.RequiredPlayerStatus
	}
	return ""
}

func (x *CheckValorantPlayerEligibilityRequest) GetMinTeammateRating() float64 {
	if x != nil {
		return x.MinTeammateRating
	}
	return 0
}

func (x *CheckValorantPlayerEligibilityRequest) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *CheckValorantPlayerEligibilityRequest) GetRequiredRoles() []string {
	if x != nil {
		return x.RequiredRoles
	}
	return nil
}

type CheckValorantPlayerEligibilityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Eligible      bool                   `protobuf:"varint,1,opt,name=eligible,proto3" json:"eligible,omitempty"`
	Reasons       []string               `protobuf:"bytes,2,rep,name=reasons,proto3" json:"reasons,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckValorantPlayerEligibilityResponse) Reset() {
	*x = CheckValorantPlayerEligibilityResponse{}
	mi := &file_valorant_player_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckValorantPlayerEligibilityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckValorantPlayerEligibilityResponse) ProtoMessage() {}

func (x *CheckValorantPlayerEligibilityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_valorant_player_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckValorantPlayerEligibilityResponse.ProtoReflect.Descriptor instead.
func (*CheckValorantPlayerEligibilityResponse) Descriptor() ([]byte, []int) {
	return file_valorant_player_service_proto_rawDescGZIP(), []int{6}
}

func (x *CheckValorantPlayerEligibilityResponse) GetEligible() bool {
	if x != nil {
		return x.Eligible
	}
	return false
}

func (x *CheckValorantPlayerEligibilityResponse) GetReasons() []string {
	if x != nil {
		return x.Reasons
	}
	return nil
}

var File_valorant_player_service_proto protoreflect.FileDescriptor

const file_valorant_player_service_proto_rawDesc = "" +
	"\n" +
	"\x1dvalorant_player_service.proto\x12\x0evalorantplayer\"8\n" +
	"\x19GetValorantProfileRequest\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\"\xc6\x02\n" +
	"\x1aGetValorantProfileResponse\x12\x16\n" +
	"\x06exists\x18\x01 \x01(\bR\x06exists\x12\x1b\n" +
	"\tplayer_id\x18\x02 \x01(\tR\bplayerId\x12\x1a\n" +
	"\bnickname\x18\x03 \x01(\tR\bnickname\x12\x17\n" +
	"\ariot_id\x18\x04 \x01(\tR\x06riotId\x12\x16\n" +
	"\x06region\x18\x05 \x01(\tR\x06region\x12!\n" +
	"\fcurrent_rank\x18\x06 \x01(\tR\vcurrentRank\x12\x1d\n" +
	"\n" +
	"main_roles\x18\a \x03(\tR\tmainRoles\x12\x16\n" +
	"\x06status\x18\b \x01(\tR\x06status\x12'\n" +
	"\x0fteammate_rating\x18\t \x01(\x01R\x0eteammateRating\x12#\n" +
	"\rreviews_count\x18\n" +
	" \x01(\x05R\freviewsCount\"\xbb\x02\n" +
	"\x1aFindValorantPlayersRequest\x12,\n" +
	"\x12excluded_player_id\x18\x01 \x01(\tR\x10excludedPlayerId\x12\x19\n" +
	"\bmin_rank\x18\x02 \x01(\tR\aminRank\x12\x19\n" +
	"\bmax_rank\x18\x03 \x01(\tR\amaxRank\x124\n" +
	"\x16required_player_status\x18\x04 \x01(\tR\x14requiredPlayerStatus\x12.\n" +
	"\x13min_teammate_rating\x18\x05 \x01(\x01R\x11minTeammateRating\x12\x16\n" +
	"\x06region\x18\x06 \x01(\tR\x06region\x12%\n" +
	"\x0erequired_roles\x18\a \x03(\tR\rrequiredRoles\x12\x14\n" +
	"\x05limit\x18\b \x01(\x05R\x05limit\"\xab\x02\n" +
	"\x17ValorantPlayerCandidate\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12\x1a\n" +
	"\bnickname\x18\x02 \x01(\tR\bnickname\x12\x17\n" +
	"\ariot_id\x18\x03 \x01(\tR\x06riotId\x12\x16\n" +
	"\x06region\x18\x04 \x01(\tR\x06region\x12!\n" +
	"\fcurrent_rank\x18\x05 \x01(\tR\vcurrentRank\x12\x1d\n" +
	"\n" +
	"main_roles\x18\x06 \x03(\tR\tmainRoles\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\x12'\n" +
	"\x0fteammate_rating\x18\b \x01(\x01R\x0eteammateRating\x12#\n" +
	"\rreviews_count\x18\t \x01(\x05R\freviewsCount\"f\n" +
	"\x1bFindValorantPlayersResponse\x12G\n" +
	"\n" +
	"candidates\x18\x01 \x03(\v2'.valorantplayer.ValorantPlayerCandidateR\n" +
	"candidates\"\x9f\x02\n" +
	"%CheckValorantPlayerEligibilityRequest\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12\x19\n" +
	"\bmin_rank\x18\x02 \x01(\tR\aminRank\x12\x19\n" +
	"\bmax_rank\x18\x03 \x01(\tR\amaxRank\x124\n" +
	"\x16required_player_status\x18\x04 \x01(\tR\x14requiredPlayerStatus\x12.\n" +
	"\x13min_teammate_rating\x18\x05 \x01(\x01R\x11minTeammateRating\x12\x16\n" +
	"\x06region\x18\x06 \x01(\tR\x06region\x12%\n" +
	"\x0erequired_roles\x18\a \x03(\tR\rrequiredRoles\"^\n" +
	"&CheckValorantPlayerEligibilityResponse\x12\x1a\n" +
	"\beligible\x18\x01 \x01(\bR\beligible\x12\x18\n" +
	"\areasons\x18\x02 \x03(\tR\areasons2\x86\x03\n" +
	"\x15ValorantPlayerService\x12k\n" +
	"\x12GetValorantProfile\x12).valorantplayer.GetValorantProfileRequest\x1a*.valorantplayer.GetValorantProfileResponse\x12n\n" +
	"\x13FindValorantPlayers\x12*.valorantplayer.FindValorantPlayersRequest\x1a+.valorantplayer.FindValorantPlayersResponse\x12\x8f\x01\n" +
	"\x1eCheckValorantPlayerEligibility\x125.valorantplayer.CheckValorantPlayerEligibilityRequest\x1a6.valorantplayer.CheckValorantPlayerEligibilityResponseB+Z)pusha/matchmaking-service/pkg/proto;protob\x06proto3"

var (
	file_valorant_player_service_proto_rawDescOnce sync.Once
	file_valorant_player_service_proto_rawDescData []byte
)

func file_valorant_player_service_proto_rawDescGZIP() []byte {
	file_valorant_player_service_proto_rawDescOnce.Do(func() {
		file_valorant_player_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_valorant_player_service_proto_rawDesc), len(file_valorant_player_service_proto_rawDesc)))
	})
	return file_valorant_player_service_proto_rawDescData
}

var file_valorant_player_service_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_valorant_player_service_proto_goTypes = []any{
	(*GetValorantProfileRequest)(nil),              // 0: valorantplayer.GetValorantProfileRequest
	(*GetValorantProfileResponse)(nil),             // 1: valorantplayer.GetValorantProfileResponse
	(*FindValorantPlayersRequest)(nil),             // 2: valorantplayer.FindValorantPlayersRequest
	(*ValorantPlayerCandidate)(nil),                // 3: valorantplayer.ValorantPlayerCandidate
	(*FindValorantPlayersResponse)(nil),            // 4: valorantplayer.FindValorantPlayersResponse
	(*CheckValorantPlayerEligibilityRequest)(nil),  // 5: valorantplayer.CheckValorantPlayerEligibilityRequest
	(*CheckValorantPlayerEligibilityResponse)(nil), // 6: valorantplayer.CheckValorantPlayerEligibilityResponse
}
var file_valorant_player_service_proto_depIdxs = []int32{
	3, // 0: valorantplayer.FindValorantPlayersResponse.candidates:type_name -> valorantplayer.ValorantPlayerCandidate
	0, // 1: valorantplayer.ValorantPlayerService.GetValorantProfile:input_type -> valorantplayer.GetValorantProfileRequest
	2, // 2: valorantplayer.ValorantPlayerService.FindValorantPlayers:input_type -> valorantplayer.FindValorantPlayersRequest
	5, // 3: valorantplayer.ValorantPlayerService.CheckValorantPlayerEligibility:input_type -> valorantplayer.CheckValorantPlayerEligibilityRequest
	1, // 4: valorantplayer.ValorantPlayerService.GetValorantProfile:output_type -> valorantplayer.GetValorantProfileResponse
	4, // 5: valorantplayer.ValorantPlayerService.FindValorantPlayers:output_type -> valorantplayer.FindValorantPlayersResponse
	6, // 6: valorantplayer.ValorantPlayerService.CheckValorantPlayerEligibility:output_type -> valorantplayer.CheckValorantPlayerEligibilityResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_valorant_player_service_proto_init() }
func file_valorant_player_service_proto_init() {
	if File_valorant_player_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_valorant_player_service_proto_rawDesc), len(file_valorant_player_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_valorant_player_service_proto_goTypes,
		DependencyIndexes: file_valorant_player_service_proto_depIdxs,
		MessageInfos:      file_valorant_player_service_proto_msgTypes,
	}.Build()
	File_valorant_player_service_proto = out.File
	file_valorant_player_service_proto_goTypes = nil
	file_valorant_player_service_proto_depIdxs = nil
}
