// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.5
// source: valorant_player_service.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ValorantPlayerService_GetValorantProfile_FullMethodName             = "/valorantplayer.ValorantPlayerService/GetValorantProfile"
	ValorantPlayerService_FindValorantPlayers_FullMethodName            = "/valorantplayer.ValorantPlayerService/FindValorantPlayers"
	ValorantPlayerService_CheckValorantPlayerEligibility_FullMethodName = "/valorantplayer.ValorantPlayerService/CheckValorantPlayerEligibility"
)

// ValorantPlayerServiceClient is the client API for ValorantPlayerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ValorantPlayerServiceClient interface {
	GetValorantProfile(ctx context.Context, in *GetValorantProfileRequest, opts ...grpc.CallOption) (*GetValorantProfileResponse, error)
	FindValorantPlayers(ctx context.Context, in *FindValorantPlayersRequest, opts ...grpc.CallOption) (*FindValorantPlayersResponse, error)
	CheckValorantPlayerEligibility(ctx context.Context, in *CheckValorantPlayerEligibilityRequest, opts ...grpc.CallOption) (*CheckValorantPlayerEligibilityResponse, error)
}

type valorantPlayerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewValorantPlayerServiceClient(cc grpc.ClientConnInterface) ValorantPlayerServiceClient {
	return &valorantPlayerServiceClient{cc}
}

func (c *valorantPlayerServiceClient) GetValorantProfile(ctx context.Context, in *GetValorantProfileRequest, opts ...grpc.CallOption) (*GetValorantProfileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetValorantProfileResponse)
	err := c.cc.Invoke(ctx, ValorantPlayerService_GetValorantProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *valorantPlayerServiceClient) FindValorantPlayers(ctx context.Context, in *FindValorantPlayersRequest, opts ...grpc.CallOption) (*FindValorantPlayersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FindValorantPlayersResponse)
	err := c.cc.Invoke(ctx, ValorantPlayerService_FindValorantPlayers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *valorantPlayerServiceClient) CheckValorantPlayerEligibility(ctx context.Context, in *CheckValorantPlayerEligibilityRequest, opts ...grpc.CallOption) (*CheckValorantPlayerEligibilityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckValorantPlayerEligibilityResponse)
	err := c.cc.Invoke(ctx, ValorantPlayerService_CheckValorantPlayerEligibility_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ValorantPlayerServiceServer is the server API for ValorantPlayerService service.
// All implementations must embed UnimplementedValorantPlayerServiceServer
// for forward compatibility.
type ValorantPlayerServiceServer interface {
	GetValorantProfile(context.Context, *GetValorantProfileRequest) (*GetValorantProfileResponse, error)
	FindValorantPlayers(context.Context, *FindValorantPlayersRequest) (*FindValorantPlayersResponse, error)
	CheckValorantPlayerEligibility(context.Context, *CheckValorantPlayerEligibilityRequest) (*CheckValorantPlayerEligibilityResponse, error)
	mustEmbedUnimplementedValorantPlayerServiceServer()
}

// UnimplementedValorantPlayerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedValorantPlayerServiceServer struct{}

func (UnimplementedValorantPlayerServiceServer) GetValorantProfile(context.Context, *GetValorantProfileRequest) (*GetValorantProfileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetValorantProfile not implemented")
}
func (UnimplementedValorantPlayerServiceServer) FindValorantPlayers(context.Context, *FindValorantPlayersRequest) (*FindValorantPlayersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FindValorantPlayers not implemented")
}
func (UnimplementedValorantPlayerServiceServer) CheckValorantPlayerEligibility(context.Context, *CheckValorantPlayerEligibilityRequest) (*CheckValorantPlayerEligibilityResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckValorantPlayerEligibility not implemented")
}
func (UnimplementedValorantPlayerServiceServer) mustEmbedUnimplementedValorantPlayerServiceServer() {}
func (UnimplementedValorantPlayerServiceServer) testEmbeddedByValue()                               {}

// UnsafeValorantPlayerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ValorantPlayerServiceServer will
// result in compilation errors.
type UnsafeValorantPlayerServiceServer interface {
	mustEmbedUnimplementedValorantPlayerServiceServer()
}

func RegisterValorantPlayerServiceServer(s grpc.ServiceRegistrar, srv ValorantPlayerServiceServer) {
	// If the following call panics, it indicates UnimplementedValorantPlayerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ValorantPlayerService_ServiceDesc, srv)
}

func _ValorantPlayerService_GetValorantProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetValorantProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ValorantPlayerServiceServer).GetValorantProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ValorantPlayerService_GetValorantProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ValorantPlayerServiceServer).GetValorantProfile(ctx, req.(*GetValorantProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ValorantPlayerService_FindValorantPlayers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindValorantPlayersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ValorantPlayerServiceServer).FindValorantPlayers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ValorantPlayerService_FindValorantPlayers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ValorantPlayerServiceServer).FindValorantPlayers(ctx, req.(*FindValorantPlayersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ValorantPlayerService_CheckValorantPlayerEligibility_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckValorantPlayerEligibilityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ValorantPlayerServiceServer).CheckValorantPlayerEligibility(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ValorantPlayerService_CheckValorantPlayerEligibility_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ValorantPlayerServiceServer).CheckValorantPlayerEligibility(ctx, req.(*CheckValorantPlayerEligibilityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ValorantPlayerService_ServiceDesc is the grpc.ServiceDesc for ValorantPlayerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ValorantPlayerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "valorantplayer.ValorantPlayerService",
	HandlerType: (*ValorantPlayerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetValorantProfile",
			Handler:    _ValorantPlayerService_GetValorantProfile_Handler,
		},
		{
			MethodName: "FindValorantPlayers",
			Handler:    _ValorantPlayerService_FindValorantPlayers_Handler,
		},
		{
			MethodName: "CheckValorantPlayerEligibility",
			Handler:    _ValorantPlayerService_CheckValorantPlayerEligibility_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "valorant_player_service.proto",
}
