package provider

import (
	"context"
	"fmt"
	"pusha/matchmaking-service/internal/domain"
	playerpb "pusha/matchmaking-service/pkg/proto"
	"time"

	"github.com/google/uuid"
	"google.golang.org/grpc"
	"google.golang.org/grpc/credentials/insecure"
)

// GrpcPlayerProvider is a PlayerProvider implementation that retrieves players
// from the Python Player Service using gRPC.
type GrpcPlayerProvider struct {
	conn   *grpc.ClientConn
	client playerpb.ValorantPlayerServiceClient
}

// NewGrpcPlayerProvider creates a gRPC-based player provider connected to the
// Python Player Service at the given address.
func NewGrpcPlayerProvider(address string) (*GrpcPlayerProvider, error) {
	conn, err := grpc.NewClient(
		address,
		grpc.WithTransportCredentials(insecure.NewCredentials()),
	)
	if err != nil {
		return nil, fmt.Errorf("create player service grpc client: %w", err)
	}

	client := playerpb.NewValorantPlayerServiceClient(conn)

	return &GrpcPlayerProvider{
		conn:   conn,
		client: client,
	}, nil
}

// Close closes the underlying gRPC client connection.
func (p *GrpcPlayerProvider) Close() error {
	return p.conn.Close()
}

// FindPlayers calls the Python Player Service and maps returned protobuf
// candidates to the internal domain.Candidate model used by the Go service.
func (p *GrpcPlayerProvider) FindPlayers(ctx context.Context, request FindPlayersRequest) ([]domain.Candidate, error) {
	response, err := p.client.FindValorantPlayers(ctx, &playerpb.FindValorantPlayersRequest{
		ExcludedPlayerId:     request.ExcludedPlayerID,
		MinRank:              request.MinRank,
		MaxRank:              request.MaxRank,
		RequiredPlayerStatus: request.RequiredPlayerStatus,
		MinTeammateRating:    request.MinTeammateRating,
		Region:               request.Region,
		RequiredRoles:        request.RequiredRoles,
		Limit:                int32(request.Limit),
	})
	if err != nil {
		return nil, fmt.Errorf("find valorant players via grpc: %w", err)
	}

	candidates := make([]domain.Candidate, 0, len(response.GetCandidates()))

	for _, grpcCandidate := range response.GetCandidates() {
		candidates = append(candidates, mapGrpcCandidateToDomainCandidate(grpcCandidate))
	}

	return candidates, nil
}

// mapGrpcCandidateToDomainCandidate converts a protobuf candidate returned by
// the Python Player Service into the internal candidate model.
//
// The internal ID is generated by the Go service because candidates are stored
// as separate matchmaking records in the Go database, while PlayerID belongs to
// the Python Player Service.
func mapGrpcCandidateToDomainCandidate(grpcCandidate *playerpb.ValorantPlayerCandidate) domain.Candidate {
	return domain.Candidate{
		ID:             uuid.NewString(),
		PlayerID:       grpcCandidate.GetPlayerId(),
		Nickname:       grpcCandidate.GetNickname(),
		RiotID:         grpcCandidate.GetRiotId(),
		CurrentRank:    grpcCandidate.GetCurrentRank(),
		Region:         grpcCandidate.GetRegion(),
		MainRoles:      grpcCandidate.GetMainRoles(),
		Status:         grpcCandidate.GetStatus(),
		TeammateRating: grpcCandidate.GetTeammateRating(),
		CreatedAt:      time.Now().UTC(),
	}
}
